name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest

    # <<< Add this env to force legacy peer deps for npm in CI >>>
    env:
      npm_config_legacy_peer_deps: 'true'
      NODE_OPTIONS: '--max-old-space-size=4096'

    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      # If you need Node setup step (optional)
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'
          cache: 'npm'

      - name: Build And Deploy
        id: swa
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_<YOUR_APP_ID> }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for GitHub integrations (i.e., PR comments)
          action: "upload"
          app_location: "/" # App source code path
          api_location: ""  # Leave empty for no functions
          output_location: "out" # location of your static export
